# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/brakeman/all/brakeman.rbi
#
# brakeman-6.0.1

module Brakeman
end
class Brakeman::DependencyError < RuntimeError
end
class Brakeman::NoBrakemanError < RuntimeError
end
class Brakeman::NoApplication < RuntimeError
end
class Brakeman::MissingChecksError < RuntimeError
end
