# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/bundler-audit/all/bundler-audit.rbi
#
# bundler-audit-0.9.1

module Bundler
end
module Bundler::Audit
end
class Bundler::Audit::Advisory < Anonymous_Struct_56
end
class Bundler::Audit::Database
end
class Bundler::Audit::Database::DownloadFailed < RuntimeError
end
class Bundler::Audit::Database::UpdateFailed < RuntimeError
end
