# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/protobuf/all/protobuf.rbi
#
# protobuf-3.10.7

module Protobuf
end
module Protobuf::WireType
end
module Protobuf::VarintPure
end
class Protobuf::Varint
  extend Protobuf::VarintPure
end
class Protobuf::Error < StandardError
end
class Protobuf::InvalidWireType < Protobuf::Error
end
class Protobuf::NotInitializedError < Protobuf::Error
end
class Protobuf::TagCollisionError < Protobuf::Error
end
class Protobuf::SerializationError < StandardError
end
class Protobuf::FieldNotDefinedError < StandardError
end
class Protobuf::DuplicateFieldNameError < StandardError
end
class Protobuf::DeprecationBase < ActiveSupport::Deprecation
end
class Protobuf::Deprecation < Protobuf::DeprecationBase
end
class Protobuf::FieldDeprecation < Protobuf::DeprecationBase
end
module Protobuf::Logging
end
class Protobuf::Encoder
end
class Protobuf::Decoder
end
module Protobuf::Optionable
end
module Protobuf::Optionable::ClassMethods
end
module Protobuf::Field
end
class Protobuf::Field::FieldArray < Array
end
class Protobuf::Field::FieldHash < Hash
end
module Protobuf::Field::BaseFieldObjectDefinitions
end
class Protobuf::Field::BaseFieldObjectDefinitions::ToHashValueToMessageHashWithStringKey
end
class Protobuf::Field::BaseFieldObjectDefinitions::BaseToMessageHashWithStringKey
end
class Protobuf::Field::BaseFieldObjectDefinitions::ToHashValueToMessageHash
end
class Protobuf::Field::BaseFieldObjectDefinitions::BaseToMessageHash
end
class Protobuf::Field::BaseFieldObjectDefinitions::RepeatedPackedEncodeToStream
end
class Protobuf::Field::BaseFieldObjectDefinitions::BytesEncodeToStream
end
class Protobuf::Field::BaseFieldObjectDefinitions::StringEncodeToStream
end
class Protobuf::Field::BaseFieldObjectDefinitions::BaseEncodeToStream
end
class Protobuf::Field::BaseFieldObjectDefinitions::RepeatedNotPackedEncodeToStream
end
class Protobuf::Field::BaseFieldObjectDefinitions::BaseSetMethod
end
class Protobuf::Field::BaseFieldObjectDefinitions::MapSetMethod
end
class Protobuf::Field::BaseFieldObjectDefinitions::RepeatedNotPackedSetMethod
end
class Protobuf::Field::BaseFieldObjectDefinitions::RepeatedPackedSetMethod
end
class Protobuf::Field::BaseFieldObjectDefinitions::RequiredMapSetField
end
class Protobuf::Field::BaseFieldObjectDefinitions::MapSetField
end
class Protobuf::Field::BaseFieldObjectDefinitions::RequiredRepeatedSetField
end
class Protobuf::Field::BaseFieldObjectDefinitions::RepeatedSetField
end
class Protobuf::Field::BaseFieldObjectDefinitions::RequiredStringSetField
end
class Protobuf::Field::BaseFieldObjectDefinitions::StringSetField
end
class Protobuf::Field::BaseFieldObjectDefinitions::RequiredBaseSetField
end
class Protobuf::Field::BaseFieldObjectDefinitions::BaseSetField
end
class Protobuf::Field::BaseFieldObjectDefinitions::BaseFieldAndPresentPredicate
end
class Protobuf::Field::BaseFieldObjectDefinitions::BoolFieldAndPresentPredicate
end
class Protobuf::Field::BaseFieldObjectDefinitions::BaseFieldPredicate
end
class Protobuf::Field::BaseFieldObjectDefinitions::RepeatedFieldPredicate
end
class Protobuf::Field::BaseFieldObjectDefinitions::BoolFieldValueFromValues
end
class Protobuf::Field::BaseFieldObjectDefinitions::BoolFieldValueFromValuesForSerialization
end
class Protobuf::Field::BaseFieldObjectDefinitions::BaseFieldValueFromValues
end
class Protobuf::Field::BaseFieldObjectDefinitions::BaseFieldValueFromValuesForSerialization
end
class Protobuf::Field::BaseFieldObjectDefinitions::MapValueFromValues
end
class Protobuf::Field::BaseFieldObjectDefinitions::MapValueFromValuesForSerialization
end
class Protobuf::Field::BaseFieldObjectDefinitions::RepeatedFieldValueFromValues
end
class Protobuf::Field::BaseFieldObjectDefinitions::RepeatedFieldValueFromValuesForSerialization
end
class Protobuf::Field::BaseField
  include Protobuf::Logging
  include Protobuf::Optionable::ClassMethods
end
class Protobuf::Field::BytesField < Protobuf::Field::BaseField
end
class Protobuf::Field::FloatField < Protobuf::Field::BaseField
end
class Protobuf::Field::MessageField < Protobuf::Field::BaseField
end
class Protobuf::Field::VarintField < Protobuf::Field::BaseField
end
class Protobuf::Field::StringField < Protobuf::Field::BytesField
end
class Protobuf::Field::DoubleField < Protobuf::Field::FloatField
end
class Protobuf::Field::IntegerField < Protobuf::Field::VarintField
end
class Protobuf::Field::EnumField < Protobuf::Field::IntegerField
end
class Protobuf::Field::SignedIntegerField < Protobuf::Field::VarintField
end
class Protobuf::Field::Uint32Field < Protobuf::Field::VarintField
end
class Protobuf::Field::Uint64Field < Protobuf::Field::VarintField
end
class Protobuf::Field::Int32Field < Protobuf::Field::IntegerField
end
class Protobuf::Field::Int64Field < Protobuf::Field::IntegerField
end
class Protobuf::Field::Sint32Field < Protobuf::Field::SignedIntegerField
end
class Protobuf::Field::Sint64Field < Protobuf::Field::SignedIntegerField
end
class Protobuf::Field::BoolField < Protobuf::Field::VarintField
end
class Protobuf::Field::Sfixed32Field < Protobuf::Field::Int32Field
end
class Protobuf::Field::Sfixed64Field < Protobuf::Field::Int64Field
end
class Protobuf::Field::Fixed32Field < Protobuf::Field::Uint32Field
end
class Protobuf::Field::Fixed64Field < Protobuf::Field::Uint64Field
end
class Protobuf::Enum < SimpleDelegator
  extend Protobuf::Optionable::ClassMethods
  include Protobuf::Optionable
end
class Protobuf::Message
  extend Protobuf::Message::Fields
  extend Protobuf::Message::Fields::ClassMethods
  extend Protobuf::Message::Serialization::ClassMethods
  extend Protobuf::Optionable::ClassMethods
  include Protobuf::Message::Serialization
  include Protobuf::Optionable
end
module Protobuf::Message::Fields
end
module Protobuf::Message::Fields::ClassMethods
end
module Protobuf::Message::Serialization
end
module Protobuf::Message::Serialization::ClassMethods
end
module Google
end
module Google::Protobuf
  extend Protobuf::Optionable::ClassMethods
  include Protobuf::Optionable
end
class Google::Protobuf::FileDescriptorSet < Protobuf::Message
end
class Google::Protobuf::FileDescriptorProto < Protobuf::Message
end
class Google::Protobuf::DescriptorProto < Protobuf::Message
end
class Google::Protobuf::DescriptorProto::ExtensionRange < Protobuf::Message
end
class Google::Protobuf::DescriptorProto::ReservedRange < Protobuf::Message
end
class Google::Protobuf::ExtensionRangeOptions < Protobuf::Message
end
class Google::Protobuf::FieldDescriptorProto < Protobuf::Message
end
class Google::Protobuf::FieldDescriptorProto::Type < Protobuf::Enum
end
class Google::Protobuf::FieldDescriptorProto::Label < Protobuf::Enum
end
class Google::Protobuf::OneofDescriptorProto < Protobuf::Message
end
class Google::Protobuf::EnumDescriptorProto < Protobuf::Message
end
class Google::Protobuf::EnumDescriptorProto::EnumReservedRange < Protobuf::Message
end
class Google::Protobuf::EnumValueDescriptorProto < Protobuf::Message
end
class Google::Protobuf::ServiceDescriptorProto < Protobuf::Message
end
class Google::Protobuf::MethodDescriptorProto < Protobuf::Message
end
class Google::Protobuf::FileOptions < Protobuf::Message
end
class Google::Protobuf::FileOptions::OptimizeMode < Protobuf::Enum
end
class Google::Protobuf::MessageOptions < Protobuf::Message
end
class Google::Protobuf::FieldOptions < Protobuf::Message
end
class Google::Protobuf::FieldOptions::CType < Protobuf::Enum
end
class Google::Protobuf::FieldOptions::JSType < Protobuf::Enum
end
class Google::Protobuf::OneofOptions < Protobuf::Message
end
class Google::Protobuf::EnumOptions < Protobuf::Message
end
class Google::Protobuf::EnumValueOptions < Protobuf::Message
end
class Google::Protobuf::ServiceOptions < Protobuf::Message
end
class Google::Protobuf::MethodOptions < Protobuf::Message
end
class Google::Protobuf::MethodOptions::IdempotencyLevel < Protobuf::Enum
end
class Google::Protobuf::UninterpretedOption < Protobuf::Message
end
class Google::Protobuf::UninterpretedOption::NamePart < Protobuf::Message
end
class Google::Protobuf::SourceCodeInfo < Protobuf::Message
end
class Google::Protobuf::SourceCodeInfo::Location < Protobuf::Message
end
class Google::Protobuf::GeneratedCodeInfo < Protobuf::Message
end
class Google::Protobuf::GeneratedCodeInfo::Annotation < Protobuf::Message
end
module Google::Protobuf::Compiler
  extend Protobuf::Optionable::ClassMethods
  include Protobuf::Optionable
end
class Google::Protobuf::Compiler::Version < Protobuf::Message
end
class Google::Protobuf::Compiler::CodeGeneratorRequest < Protobuf::Message
end
class Google::Protobuf::Compiler::CodeGeneratorResponse < Protobuf::Message
end
class Google::Protobuf::Compiler::CodeGeneratorResponse::Feature < Protobuf::Enum
end
class Google::Protobuf::Compiler::CodeGeneratorResponse::File < Protobuf::Message
end
module Protobuf::Socketrpc
  extend Protobuf::Optionable::ClassMethods
  include Protobuf::Optionable
end
class Protobuf::Socketrpc::ErrorReason < Protobuf::Enum
end
class Protobuf::Socketrpc::Request < Protobuf::Message
end
class Protobuf::Socketrpc::Response < Protobuf::Message
end
class Protobuf::Socketrpc::Header < Protobuf::Message
end
module Protobuf::Rpc
end
class Protobuf::Rpc::BadRequestData < Protobuf::Rpc::PbError
end
class Protobuf::Rpc::BadRequestProto < Protobuf::Rpc::PbError
end
class Protobuf::Rpc::ServiceNotFound < Protobuf::Rpc::PbError
end
class Protobuf::Rpc::MethodNotFound < Protobuf::Rpc::PbError
end
class Protobuf::Rpc::RpcError < Protobuf::Rpc::PbError
end
class Protobuf::Rpc::RpcFailed < Protobuf::Rpc::PbError
end
class Protobuf::Rpc::InvalidRequestProto < Protobuf::Rpc::PbError
end
class Protobuf::Rpc::BadResponseProto < Protobuf::Rpc::PbError
end
class Protobuf::Rpc::UnkownHost < Protobuf::Rpc::PbError
end
class Protobuf::Rpc::IOError < Protobuf::Rpc::PbError
end
class Protobuf::Rpc::PbError < StandardError
end
class Protobuf::Rpc::Client
  extend Forwardable
  include Protobuf::Logging
end
class Protobuf::Rpc::RpcMethod
  include Protobuf::Optionable::ClassMethods
end
module Protobuf::Rpc::ServiceFilters
end
module Protobuf::Rpc::ServiceFilters::ClassMethods
end
module Protobuf::Rpc::ServiceFilters::InstanceMethods
end
class Protobuf::Rpc::Service
  extend Protobuf::Optionable::ClassMethods
  extend Protobuf::Rpc::ServiceFilters::ClassMethods
  include Protobuf::Logging
  include Protobuf::Optionable
  include Protobuf::Rpc::ServiceFilters
  include Protobuf::Rpc::ServiceFilters::InstanceMethods
end
class Protobuf::Rpc::Buffer
end
class Protobuf::Rpc::Env < Hash
end
module Protobuf::Rpc::Middleware
end
class Protobuf::Rpc::Middleware::ExceptionHandler
  include Protobuf::Logging
end
class Protobuf::Rpc::Middleware::Logger
end
class Protobuf::Rpc::Middleware::Logger::Instrumenter
end
class Protobuf::Rpc::Middleware::RequestDecoder
  include Protobuf::Logging
end
class Protobuf::Rpc::Middleware::ResponseEncoder
  include Protobuf::Logging
end
class Protobuf::Rpc::Middleware::Runner < Middleware::Runner
end
class Protobuf::Rpc::ServiceDispatcher
  include Protobuf::Logging
end
module Protobuf::Rpc::Server
end
module Protobuf::Rpc::Socket
end
class Protobuf::Rpc::Socket::Worker
  include Protobuf::Logging
  include Protobuf::Rpc::Server
end
class Protobuf::Rpc::Socket::Server
  include Protobuf::Logging
end
class Protobuf::Rpc::Stat
end
module Protobuf::Rpc::Connectors
end
class Protobuf::Rpc::Connectors::Base
  include Protobuf::Logging
end
class Protobuf::Rpc::Connectors::Socket < Protobuf::Rpc::Connectors::Base
  include Protobuf::Logging
end
